version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0-stretch-node-browsers-legacy
        auth:
          username: pauloprsdesouza
          password: P4ul!nh0r2  # context / project UI env-var referenc
    steps:
      - checkout
      - run : mvn test
      - store_artifacts:
          path:  target
      - codecov/upload:
          file: 'target/my-reports'
          token: '5c2006b7-3d49-49b4-85ce-e58fbafe043a'

